FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore --use-current-runtime

# copy and publish app and libraries
COPY . .
RUN dotnet publish  -c Release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/nightly/aspnet:6.0-jammy-chiseled
EXPOSE 8080
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "dotnetapp.dll"]